# Generated by Django 3.2.2 on 2021-05-07 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newword', '0002_auto_20210507_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='score',
            field=models.FloatField(null=True),
        ),
    ]
