# Generated by Django 3.2.2 on 2021-05-09 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newword', '0007_alter_test_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newword',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='words', to='newword.lesson'),
        ),
        migrations.AlterField(
            model_name='newword',
            name='wtype',
            field=models.IntegerField(choices=[(1, 'Noun'), (2, 'Verb'), (3, 'Adjective'), (4, 'Adverb'), (5, 'Phrasal verb/Preposition')], default=1),
        ),
    ]
