# Generated by Django 3.2.2 on 2021-05-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newword', '0008_auto_20210509_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='correct',
            field=models.IntegerField(blank=True, choices=[(0, 'False'), (1, 'True')], null=True),
        ),
    ]
